name: sardinia-fires
channels:
- conda-forge
- defaults
dependencies:
- backcall=0.1.0=py_0
- backports=1.0=py36_1
- backports.functools_lru_cache=1.5=py_1
- bleach=2.1.3=py_0
- boost=1.67.0=py36h3e44d54_0
- boost-cpp=1.67.0=h3a22d5f_0
- bzip2=1.0.6=h470a237_2
- cairo=1.14.6=5
- click=6.7=py_1
- click-plugins=1.0.3=py_1
- cligj=0.4.0=py36_0
- cycler=0.10.0=py_1
- dbus=1.11.0=0
- decorator=4.3.0=py_0
- descartes=1.1.0=py_1
- entrypoints=0.2.3=py36_1
- expat=2.1.0=3
- fiona=1.7.9=py36_1
- fontconfig=2.12.1=6
- freetype=2.7=2
- freexl=1.0.5=hf837533_1
- gdal=2.1.3=py36_7
- geopandas=0.3.0=py_1
- geos=3.6.2=hfc679d8_2
- gettext=0.19.8.1=0
- giflib=5.1.4=h470a237_0
- glib=2.51.4=0
- gmp=6.1.2=hfc679d8_0
- gst-plugins-base=1.8.0=0
- gstreamer=1.8.0=2
- hdf4=4.2.13=0
- hdf5=1.10.1=2
- html5lib=1.0.1=py_0
- icu=58.2=hfc679d8_0
- ipykernel=4.8.2=py36_0
- ipython=6.4.0=py36_0
- ipython_genutils=0.2.0=py_1
- ipywidgets=7.2.1=py36_1
- jedi=0.12.1=py36_0
- jinja2=2.10=py_1
- jpeg=9c=h470a237_0
- jsonschema=2.6.0=py36_1
- jupyter=1.0.0=py_1
- jupyter_client=5.2.3=py_1
- jupyter_console=5.2.0=py36_0
- jupyter_core=4.4.0=py_0
- kealib=1.4.8=hfc679d8_0
- kiwisolver=1.0.1=py36_1
- krb5=1.14.6=0
- libdap4=3.18.3=2
- libiconv=1.15=h470a237_1
- libnetcdf=4.4.1.1=10
- libpng=1.6.28=2
- libpq=9.6.3=0
- libsodium=1.0.16=0
- libspatialindex=1.8.5=hfc679d8_2
- libspatialite=4.3.0a=18
- libssh2=1.8.0=h5b517e9_2
- libtiff=4.0.9=he6b73bb_1
- libuuid=1.0.3=1
- libxcb=1.13=h470a237_1
- libxml2=2.9.8=h422b904_2
- markupsafe=1.0=py36_0
- matplotlib=2.1.1=py36_0
- mistune=0.8.3=py36_1
- mkl_fft=1.0.2=py36_0
- mkl_random=1.0.1=py36_0
- munch=2.3.2=py_0
- nbconvert=5.3.1=py_1
- nbformat=4.4.0=py36_0
- notebook=5.5.0=py36_0
- openjpeg=2.1.2=3
- pandas=0.23.3=py36_0
- pandoc=2.2.1=0
- pandocfilters=1.4.2=py_1
- parso=0.3.0=py_0
- pexpect=4.6.0=py36_0
- pickleshare=0.7.4=py36_0
- pixman=0.34.0=2
- poppler=0.52.0=2
- poppler-data=0.4.9=0
- proj4=4.9.3=5
- prompt_toolkit=1.0.15=py36_0
- psycopg2=2.7.5=py36_0
- pthread-stubs=0.4=h470a237_1
- ptyprocess=0.6.0=py36_0
- pygments=2.2.0=py_1
- pyparsing=2.2.0=py_1
- pyproj=1.9.5.1=py36_0
- pysal=1.14.3=py36_0
- python-dateutil=2.7.3=py_0
- pytz=2018.5=py_0
- pyzmq=17.1.0=py36hae99301_0
- qt=5.6.2=6
- qtconsole=4.3.1=py36_0
- rtree=0.8.3=py36_0
- send2trash=1.5.0=py_0
- shapely=1.6.4=py36h164cb2d_1
- simplegeneric=0.8.1=py_1
- six=1.11.0=py36_1
- sqlalchemy=1.2.9=py36_0
- sqlite=3.13.0=1
- terminado=0.8.1=py36_0
- testpath=0.3.1=py36_0
- tornado=5.1=py36_0
- traitlets=4.3.2=py36_0
- wcwidth=0.1.7=py_1
- webencodings=0.5=py36_0
- widgetsnbextension=3.2.1=py36_0
- xerces-c=3.2.0=0
- xorg-libxau=1.0.8=h470a237_5
- xorg-libxdmcp=1.1.2=h470a237_6
- zeromq=4.2.5=hfc679d8_3
- ca-certificates=2018.03.07=0
- certifi=2018.4.16=py36_0
- curl=7.60.0=h84994c4_0
- intel-openmp=2018.0.3=0
- json-c=0.13.1=h1bed415_0
- libboost=1.65.1=habcd387_4
- libcurl=7.60.0=h1ad7b7a_0
- libedit=3.1.20170329=h6b74fdf_2
- libffi=3.2.1=hd88cf55_4
- libgcc=7.2.0=h69d50b8_2
- libgcc-ng=7.2.0=hdf63c60_3
- libgdal=2.0.0=1
- libgfortran=3.0.0=1
- libgfortran-ng=7.2.0=hdf63c60_3
- libkml=1.3.0=h8777076_2
- libstdcxx-ng=7.2.0=hdf63c60_3
- mkl=2018.0.3=1
- ncurses=6.1=hf484d3e_0
- numpy=1.14.2=py36hdbf6ddf_1
- openssl=1.0.2o=h20670df_0
- pcre=8.42=h439df22_0
- pip=10.0.1=py36_0
- pyqt=5.6.0=py36_2
- python=3.6.2=0
- readline=6.2=2
- scipy=1.1.0=py36hfc37229_0
- setuptools=39.2.0=py36_0
- sip=4.19.8=py36hf484d3e_0
- tk=8.5.18=0
- util-linux=2.21=0
- wheel=0.31.1=py36_0
- xz=5.2.4=h14c3975_4
- zlib=1.2.11=ha838bed_2
- pip:
  - awscli==1.15.14
  - backports.functools-lru-cache==1.5
  - botocore==1.10.14
  - colorama==0.3.7
  - docutils==0.14
  - ipython-genutils==0.2.0
  - jmespath==0.9.3
  - jupyter-client==5.2.3
  - jupyter-console==5.2.0
  - jupyter-core==4.4.0
  - mkl-fft==1.0.2
  - mkl-random==1.0.1
  - prompt-toolkit==1.0.15
  - pyasn1==0.4.2
  - pyyaml==3.12
  - rsa==3.4.2
  - s3transfer==0.1.13
prefix: /home/jack/miniconda3/envs/sardinia-fires

